python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
before_install:
  # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq


install:
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n test-environment python=2.7 numpy scipy matplotlib pandas=0.18.1 nose requests pyserial netcdf4 cython numexpr
  - source activate test-environment
  - pip install -r requirements.txt
  - pip install codecov
#  - git clone https://github.com/lmfit/lmfit-py
#  - cd lmfit-py; pip install .; cd ..
  - git clone https://github.com/nrao/ValonSynth.git
  - cd ValonSynth; python setup.py install; cd ..
#  - python setup.py install
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform



after_success:
  - codecov
# command to run tests
script: 
  - nosetests -v --with-coverage --cover-erase --cover-xml --cover-inclusive --cover-package=kid_readout --exclude=".*equipment.*" --ignore-files="setup.py|interactive.py" --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_kid_readout_5772b9df5a_3
  - python -m properform Push 47.88.50.110:15554 asdf_kid_readout_5772b9df5a_3 ./profile_kid_readout_5772b9df5a_3


#2017-08-10 09:12:21 modified at 0#2017-08-10 09:12:33 modified at 1#2017-08-10 09:12:39 modified at 2#2017-08-10 09:12:46 modified at 3