python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"

before_install:
  # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq



install:
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n test-environment python=2.7 numpy scipy nose pandas matplotlib
  - source activate test-environment
  - pip install -r requirements.txt
  - pip install codecov
#  - python setup.py installl
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform

after_success:
  - codecov
# command to run tests
script: 
  - nosetests --cover-erase --cover-html --cover-xml --with-coverage --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_kid_readout_29f4cad456_2
  - python -m properform Push 47.88.50.110:15554 asdf_kid_readout_29f4cad456_2 ./profile_kid_readout_29f4cad456_2


#2017-08-10 11:59:36 modified at 0#2017-08-10 11:59:42 modified at 1#2017-08-10 11:59:48 modified at 2